#!/usr/bin/env bash
#
# gen_syscall_names.sh - generate syscall_names.h from the system headers.
#
# Rather than hand-typing a 350-entry table (which goes stale every kernel
# release and is wrong on any other architecture), ask the preprocessor for
# every __NR_* macro it knows about and turn them into a designated-initialiser
# array indexed by syscall number.
#
#     ./gen_syscall_names.sh > syscall_names.h
#
set -euo pipefail

CC="${CC:-gcc}"

printf '/* AUTO-GENERATED by gen_syscall_names.sh - do not edit by hand. */\n'
printf '/* Generated on %s for %s */\n\n' "$(date '+%Y-%m-%d')" "$(uname -m)"
printf '#ifndef SYSCALL_NAMES_H\n#define SYSCALL_NAMES_H\n\n'
printf 'static const char *const syscall_names[] = {\n'

# -dM dumps every macro the preprocessor has defined after reading the header.
# __NR_read is defined as a plain integer on x86-64; on some architectures it
# is an expression like (__NR_Linux + 5), so non-numeric values are skipped.
echo '#include <sys/syscall.h>' \
  | "$CC" -E -dM -x c - \
  | awk '
      /^#define __NR_[A-Za-z0-9_]+ [0-9]+$/ {
          name = substr($2, 6)          # strip the leading "__NR_" (awk is 1-indexed)
          printf "    [%s] = \"%s\",\n", $3, name
      }
  ' \
  | sort -t'[' -k2 -n

printf '};\n\n'
printf '#define SYSCALL_NAMES_COUNT \\\n'
printf '    ((long)(sizeof syscall_names / sizeof syscall_names[0]))\n\n'
printf '#endif /* SYSCALL_NAMES_H */\n'
