/*
 * ptrace_common.c - see ptrace_common.h.
 */
#define _GNU_SOURCE
#include "ptrace_common.h"
#include "syscall_names.h"      /* generated by gen_syscall_names.sh */

#include <sys/ptrace.h>
#include <sys/syscall.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <limits.h>     /* PATH_MAX */

const char *sc_name(long nr)
{
    if (nr >= 0 && nr < SYSCALL_NAMES_COUNT && syscall_names[nr] != NULL)
        return syscall_names[nr];
    return "unknown";
}

const char *errno_symbol(int e)
{
    switch (e) {
    case EPERM:   return "EPERM";
    case ENOENT:  return "ENOENT";
    case ESRCH:   return "ESRCH";
    case EINTR:   return "EINTR";
    case EIO:     return "EIO";
    case EBADF:   return "EBADF";
    case EAGAIN:  return "EAGAIN";
    case ENOMEM:  return "ENOMEM";
    case EACCES:  return "EACCES";
    case EFAULT:  return "EFAULT";
    case EEXIST:  return "EEXIST";
    case ENODEV:  return "ENODEV";
    case ENOTDIR: return "ENOTDIR";
    case EISDIR:  return "EISDIR";
    case EINVAL:  return "EINVAL";
    case ENOTTY:  return "ENOTTY";
    case ESPIPE:  return "ESPIPE";
    case EPIPE:   return "EPIPE";
    case ERANGE:  return "ERANGE";
    case ENOSYS:  return "ENOSYS";
    case ELOOP:   return "ELOOP";
    default:      return NULL;
    }
}

void regs_get_args(const struct user_regs_struct *r, unsigned long args[SC_NARGS])
{
    args[0] = (unsigned long)r->rdi;
    args[1] = (unsigned long)r->rsi;
    args[2] = (unsigned long)r->rdx;
    args[3] = (unsigned long)r->r10;   /* r10, not rcx - SYSCALL clobbers rcx */
    args[4] = (unsigned long)r->r8;
    args[5] = (unsigned long)r->r9;
}

/* ------------------------------------------------- tracee memory access */

long tracee_read_string(pid_t pid, unsigned long addr, char *out, size_t outsz)
{
    size_t copied = 0;

    if (addr == 0 || outsz == 0)
        return -1;

    while (copied < outsz - 1) {
        /*
         * PTRACE_PEEKDATA returns the word it read as the function's return
         * value, so -1 is a legitimate value. The documented way to tell a
         * real error apart from the data 0xffffffffffffffff is to clear
         * errno first and check it afterwards.
         */
        errno = 0;
        long word = ptrace(PTRACE_PEEKDATA, pid, addr + copied, NULL);
        if (word == -1 && errno != 0)
            return -1;

        /* Copy the word byte by byte, stopping at the string terminator. */
        char bytes[sizeof(long)];
        memcpy(bytes, &word, sizeof word);

        for (size_t i = 0; i < sizeof word && copied < outsz - 1; i++) {
            out[copied++] = bytes[i];
            if (bytes[i] == '\0')
                return (long)(copied - 1);
        }
    }

    out[copied] = '\0';
    return (long)copied;
}

int tracee_write_mem(pid_t pid, unsigned long addr, const void *src, size_t len)
{
    char path[64];
    int fd;
    ssize_t n;

    /*
     * /proc/<pid>/mem is the simple way to write an arbitrary run of bytes.
     * PTRACE_POKEDATA would also work but only moves one word at a time and
     * would need a read-modify-write for the trailing partial word.
     * The tracee must be ptrace-stopped by us for this to be permitted.
     */
    snprintf(path, sizeof path, "/proc/%d/mem", (int)pid);
    fd = open(path, O_WRONLY);
    if (fd < 0)
        return -1;

    n = pwrite(fd, src, len, (off_t)addr);
    close(fd);

    return (n == (ssize_t)len) ? 0 : -1;
}

int tracee_read_mem(pid_t pid, unsigned long addr, void *dst, size_t len)
{
    char path[64];
    int fd;
    ssize_t n;

    snprintf(path, sizeof path, "/proc/%d/mem", (int)pid);
    fd = open(path, O_RDONLY);
    if (fd < 0)
        return -1;

    n = pread(fd, dst, len, (off_t)addr);
    close(fd);

    return (n == (ssize_t)len) ? 0 : -1;
}

/* ----------------------------------------------------------- formatting */

void open_flags_text(long flags, char *out, size_t outsz)
{
    static const struct { int bit; const char *name; } table[] = {
        { O_CREAT,     "O_CREAT"     },
        { O_EXCL,      "O_EXCL"      },
        { O_NOCTTY,    "O_NOCTTY"    },
        { O_TRUNC,     "O_TRUNC"     },
        { O_APPEND,    "O_APPEND"    },
        { O_NONBLOCK,  "O_NONBLOCK"  },
        { O_DIRECTORY, "O_DIRECTORY" },
        { O_NOFOLLOW,  "O_NOFOLLOW"  },
        { O_CLOEXEC,   "O_CLOEXEC"   },
        { O_DIRECT,    "O_DIRECT"    },
        { O_LARGEFILE, "O_LARGEFILE" },
    };
    int accmode = (int)(flags & O_ACCMODE);
    size_t used;

    const char *acc = (accmode == O_RDONLY) ? "O_RDONLY"
                    : (accmode == O_WRONLY) ? "O_WRONLY"
                    : (accmode == O_RDWR)   ? "O_RDWR"
                    : "O_?";
    used = (size_t)snprintf(out, outsz, "%s", acc);

    for (size_t i = 0; i < sizeof table / sizeof table[0]; i++) {
        if ((flags & table[i].bit) && used < outsz - 1)
            used += (size_t)snprintf(out + used, outsz - used, "|%s", table[i].name);
    }
}

/* Quote a string for display, escaping the characters strace escapes. */
static void quote_string(const char *s, char *out, size_t outsz)
{
    size_t o = 0;

    if (o < outsz - 1) out[o++] = '"';
    for (size_t i = 0; s[i] != '\0' && o < outsz - 6; i++) {
        unsigned char c = (unsigned char)s[i];
        switch (c) {
        case '\n': out[o++] = '\\'; out[o++] = 'n';  break;
        case '\t': out[o++] = '\\'; out[o++] = 't';  break;
        case '\r': out[o++] = '\\'; out[o++] = 'r';  break;
        case '"':  out[o++] = '\\'; out[o++] = '"';  break;
        case '\\': out[o++] = '\\'; out[o++] = '\\'; break;
        default:
            if (c < 32 || c > 126)
                o += (size_t)snprintf(out + o, outsz - o, "\\%03o", c);
            else
                out[o++] = (char)c;
        }
    }
    if (o < outsz - 1) out[o++] = '"';
    out[o] = '\0';
}

/*
 * Render the dirfd argument of the *at() family.
 *
 * File descriptors are ints, so a negative one such as AT_FDCWD (-100) sits
 * in the low 32 bits of a 64-bit register with the upper half zero. It has
 * to be narrowed to int before comparing or printing, otherwise AT_FDCWD
 * shows up as 4294967196.
 */
static const char *dirfd_text(long fd, char *scratch, size_t sz)
{
    int fd32 = (int)fd;

    if (fd32 == AT_FDCWD)
        return "AT_FDCWD";
    snprintf(scratch, sz, "%d", fd32);
    return scratch;
}

/*
 * Read a string argument out of the tracee and quote it; on failure fall
 * back to showing the raw pointer, which is what strace does too.
 */
static void arg_as_path(pid_t pid, unsigned long addr, char *out, size_t outsz)
{
    char raw[PATH_MAX];

    if (tracee_read_string(pid, addr, raw, sizeof raw) < 0)
        snprintf(out, outsz, "0x%lx", addr);
    else
        quote_string(raw, out, outsz);
}

void format_syscall_args(pid_t pid, long nr,
                         const unsigned long args[SC_NARGS],
                         char *out, size_t outsz)
{
    char p[PATH_MAX + 16], flagbuf[160], fdbuf[32];

    switch (nr) {
    case SYS_openat:
        arg_as_path(pid, args[1], p, sizeof p);
        open_flags_text((long)args[2], flagbuf, sizeof flagbuf);
        if (args[2] & O_CREAT)
            snprintf(out, outsz, "%s, %s, %s, 0%03o",
                     dirfd_text((long)args[0], fdbuf, sizeof fdbuf),
                     p, flagbuf, (unsigned)args[3]);
        else
            snprintf(out, outsz, "%s, %s, %s",
                     dirfd_text((long)args[0], fdbuf, sizeof fdbuf), p, flagbuf);
        break;

    case SYS_open:
        arg_as_path(pid, args[0], p, sizeof p);
        open_flags_text((long)args[1], flagbuf, sizeof flagbuf);
        snprintf(out, outsz, "%s, %s", p, flagbuf);
        break;

    case SYS_read:
    case SYS_write:
        snprintf(out, outsz, "%d, 0x%lx, %lu",
                 (int)args[0], args[1], args[2]);
        break;

    case SYS_close:
        snprintf(out, outsz, "%d", (int)args[0]);
        break;

    case SYS_fstat:
    case SYS_getdents64:
        snprintf(out, outsz, "%d, 0x%lx", (int)args[0], args[1]);
        break;

    case SYS_newfstatat:
        arg_as_path(pid, args[1], p, sizeof p);
        snprintf(out, outsz, "%s, %s, 0x%lx, %ld",
                 dirfd_text((long)args[0], fdbuf, sizeof fdbuf),
                 p, args[2], (long)args[3]);
        break;

    case SYS_stat:
    case SYS_lstat:
    case SYS_chdir:
    case SYS_unlink:
    case SYS_rmdir:
    case SYS_readlink:
    case SYS_access:
    case SYS_execve:
        arg_as_path(pid, args[0], p, sizeof p);
        snprintf(out, outsz, "%s, ...", p);
        break;

    case SYS_mmap:
        snprintf(out, outsz, "0x%lx, %lu, 0x%lx, 0x%lx, %d, %ld",
                 args[0], args[1], args[2], args[3], (int)args[4], (long)args[5]);
        break;

    case SYS_exit_group:
        snprintf(out, outsz, "%ld", (long)args[0]);
        break;

    default:
        /* Unknown shape - show the first three words in hex, like strace. */
        snprintf(out, outsz, "0x%lx, 0x%lx, 0x%lx", args[0], args[1], args[2]);
        break;
    }
}

void format_syscall_ret(long nr, long ret, char *out, size_t outsz)
{
    /*
     * The kernel reports failure as a small negative errno in rax. libc
     * turns that into -1 with errno set; here we see the raw form.
     */
    if (ret < 0 && ret > -4096) {
        const char *sym = errno_symbol((int)-ret);
        if (sym != NULL)
            snprintf(out, outsz, "-1 %s (%s)", sym, strerror((int)-ret));
        else
            snprintf(out, outsz, "-1 errno=%ld (%s)", -ret, strerror((int)-ret));
        return;
    }

    /* mmap and brk return addresses, which read better in hex. */
    if (nr == SYS_mmap || nr == SYS_brk || nr == SYS_mremap)
        snprintf(out, outsz, "0x%lx", (unsigned long)ret);
    else
        snprintf(out, outsz, "%ld", ret);
}
